title: Reactive Record
email: kyle@reactiverecord.com
description: Communicate with JSON APIs in React.
baseurl:
url: https://reactiverecord.com
aux_links:
  GitHub:
    - https://github.com/kyleramirez/reactiverecord
  NPM:
    - https://www.npmjs.com/package/reactiverecord
# Build settings
markdown: kramdown
permalink: /:categories/:title
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
