title: Reactive Record
email: kyle@reactiverecord.com
description: Communicate with JSON APIs in React.
baseurl:
url: https://reactiverecord.com
aux_links:
  GitHub:
    - https://github.com/reactiverecord/reactiverecord
  NPM:
    - https://www.npmjs.com/package/reactiverecord
search_enabled: true
# Build settings
markdown: kramdown
permalink: /:categories/:title
remote_theme: pmarsceill/just-the-docs@v0.2.8
logo: /assets/images/wordmark-site.png
plugins:
  - jekyll-feed
